language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install: gem install bundler -v 1.16.1
env:
  - RAILS_VERSION=5.2
  - RAILS_VERSION=6.0
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.4
      env: RAILS_VERSION=6.0
